### ISSUE TITLE
Create example database

### ISSUE THREAD

**Issue by agorlov** [agorlov/lipid-example#1]

**Comment by 0pdd** [comment]
@agorlov 5 puzzles [#4](https://github.com/agorlov/lipid-example/issues/4), [#5](https://github.com/agorlov/lipid-example/issues/5), [#6](https://github.com/agorlov/lipid-example/issues/6), [#7](https://github.com/agorlov/lipid-example/issues/7), [#8](https://github.com/agorlov/lipid-example/issues/8) are still not solved.

**Comment by 0pdd** [comment]
@agorlov 4 puzzles [#5](https://github.com/agorlov/lipid-example/issues/5), [#6](https://github.com/agorlov/lipid-example/issues/6), [#7](https://github.com/agorlov/lipid-example/issues/7), [#8](https://github.com/agorlov/lipid-example/issues/8) are still not solved; solved: [#4](https://github.com/agorlov/lipid-example/issues/4).

**Comment by 0pdd** [comment]
@agorlov 11 puzzles [#33](https://github.com/agorlov/lipid-example/issues/33), [#34](https://github.com/agorlov/lipid-example/issues/34), [#35](https://github.com/agorlov/lipid-example/issues/35), [#36](https://github.com/agorlov/lipid-example/issues/36), [#37](https://github.com/agorlov/lipid-example/issues/37), [#38](https://github.com/agorlov/lipid-example/issues/38), [#39](https://github.com/agorlov/lipid-example/issues/39), [#40](https://github.com/agorlov/lipid-example/issues/40), [#41](https://github.com/agorlov/lipid-example/issues/41), [#42](https://github.com/agorlov/lipid-example/issues/42), [#43](https://github.com/agorlov/lipid-example/issues/43) are still not solved; solved: [#4](https://github.com/agorlov/lipid-example/issues/4), [#5](https://github.com/agorlov/lipid-example/issues/5), [#6](https://github.com/agorlov/lipid-example/issues/6), [#7](https://github.com/agorlov/lipid-example/issues/7), [#8](https://github.com/agorlov/lipid-example/issues/8).

**Comment by 0pdd** [comment]
@agorlov 10 puzzles [#34](https://github.com/agorlov/lipid-example/issues/34), [#35](https://github.com/agorlov/lipid-example/issues/35), [#36](https://github.com/agorlov/lipid-example/issues/36), [#37](https://github.com/agorlov/lipid-example/issues/37), [#38](https://github.com/agorlov/lipid-example/issues/38), [#39](https://github.com/agorlov/lipid-example/issues/39), [#40](https://github.com/agorlov/lipid-example/issues/40), [#41](https://github.com/agorlov/lipid-example/issues/41), [#42](https://github.com/agorlov/lipid-example/issues/42), [#43](https://github.com/agorlov/lipid-example/issues/43) are still not solved; solved: [#33](https://github.com/agorlov/lipid-example/issues/33), [#4](https://github.com/agorlov/lipid-example/issues/4), [#5](https://github.com/agorlov/lipid-example/issues/5), [#6](https://github.com/agorlov/lipid-example/issues/6), [#7](https://github.com/agorlov/lipid-example/issues/7), [#8](https://github.com/agorlov/lipid-example/issues/8).

**Comment by 0pdd** [comment]
@agorlov 9 puzzles [#34](https://github.com/agorlov/lipid-example/issues/34), [#36](https://github.com/agorlov/lipid-example/issues/36), [#37](https://github.com/agorlov/lipid-example/issues/37), [#38](https://github.com/agorlov/lipid-example/issues/38), [#39](https://github.com/agorlov/lipid-example/issues/39), [#40](https://github.com/agorlov/lipid-example/issues/40), [#41](https://github.com/agorlov/lipid-example/issues/41), [#42](https://github.com/agorlov/lipid-example/issues/42), [#43](https://github.com/agorlov/lipid-example/issues/43) are still not solved; solved: [#33](https://github.com/agorlov/lipid-example/issues/33), [#35](https://github.com/agorlov/lipid-example/issues/35), [#4](https://github.com/agorlov/lipid-example/issues/4), [#5](https://github.com/agorlov/lipid-example/issues/5), [#6](https://github.com/agorlov/lipid-example/issues/6), [#7](https://github.com/agorlov/lipid-example/issues/7), [#8](https://github.com/agorlov/lipid-example/issues/8).

**Comment by 0pdd** [comment]
@agorlov 8 puzzles [#36](https://github.com/agorlov/lipid-example/issues/36), [#37](https://github.com/agorlov/lipid-example/issues/37), [#38](https://github.com/agorlov/lipid-example/issues/38), [#39](https://github.com/agorlov/lipid-example/issues/39), [#40](https://github.com/agorlov/lipid-example/issues/40), [#41](https://github.com/agorlov/lipid-example/issues/41), [#42](https://github.com/agorlov/lipid-example/issues/42), [#43](https://github.com/agorlov/lipid-example/issues/43) are still not solved; solved: [#33](https://github.com/agorlov/lipid-example/issues/33), [#34](https://github.com/agorlov/lipid-example/issues/34), [#35](https://github.com/agorlov/lipid-example/issues/35), [#4](https://github.com/agorlov/lipid-example/issues/4), [#5](https://github.com/agorlov/lipid-example/issues/5), [#6](https://github.com/agorlov/lipid-example/issues/6), [#7](https://github.com/agorlov/lipid-example/issues/7), [#8](https://github.com/agorlov/lipid-example/issues/8).

**Comment by 0pdd** [comment]
@agorlov 6 puzzles [#36](https://github.com/agorlov/lipid-example/issues/36), [#37](https://github.com/agorlov/lipid-example/issues/37), [#39](https://github.com/agorlov/lipid-example/issues/39), [#40](https://github.com/agorlov/lipid-example/issues/40), [#42](https://github.com/agorlov/lipid-example/issues/42), [#43](https://github.com/agorlov/lipid-example/issues/43) are still not solved; solved: [#33](https://github.com/agorlov/lipid-example/issues/33), [#34](https://github.com/agorlov/lipid-example/issues/34), [#35](https://github.com/agorlov/lipid-example/issues/35), [#38](https://github.com/agorlov/lipid-example/issues/38), [#41](https://github.com/agorlov/lipid-example/issues/41), [#4](https://github.com/agorlov/lipid-example/issues/4), [#5](https://github.com/agorlov/lipid-example/issues/5), [#6](https://github.com/agorlov/lipid-example/issues/6), [#7](https://github.com/agorlov/lipid-example/issues/7), [#8](https://github.com/agorlov/lipid-example/issues/8).

**Comment by 0pdd** [comment]
@agorlov 5 puzzles [#36](https://github.com/agorlov/lipid-example/issues/36), [#37](https://github.com/agorlov/lipid-example/issues/37), [#39](https://github.com/agorlov/lipid-example/issues/39), [#40](https://github.com/agorlov/lipid-example/issues/40), [#42](https://github.com/agorlov/lipid-example/issues/42) are still not solved; solved: [#33](https://github.com/agorlov/lipid-example/issues/33), [#34](https://github.com/agorlov/lipid-example/issues/34), [#35](https://github.com/agorlov/lipid-example/issues/35), [#38](https://github.com/agorlov/lipid-example/issues/38), [#41](https://github.com/agorlov/lipid-example/issues/41), [#43](https://github.com/agorlov/lipid-example/issues/43), [#4](https://github.com/agorlov/lipid-example/issues/4), [#5](https://github.com/agorlov/lipid-example/issues/5), [#6](https://github.com/agorlov/lipid-example/issues/6), [#7](https://github.com/agorlov/lipid-example/issues/7), [#8](https://github.com/agorlov/lipid-example/issues/8).

**Comment by 0pdd** [comment]
@agorlov 5 puzzles [#36](https://github.com/agorlov/lipid-example/issues/36), [#39](https://github.com/agorlov/lipid-example/issues/39), [#40](https://github.com/agorlov/lipid-example/issues/40), [#42](https://github.com/agorlov/lipid-example/issues/42), [#51](https://github.com/agorlov/lipid-example/issues/51) are still not solved; solved: [#33](https://github.com/agorlov/lipid-example/issues/33), [#34](https://github.com/agorlov/lipid-example/issues/34), [#35](https://github.com/agorlov/lipid-example/issues/35), [#37](https://github.com/agorlov/lipid-example/issues/37), [#38](https://github.com/agorlov/lipid-example/issues/38), [#41](https://github.com/agorlov/lipid-example/issues/41), [#43](https://github.com/agorlov/lipid-example/issues/43), [#4](https://github.com/agorlov/lipid-example/issues/4), [#5](https://github.com/agorlov/lipid-example/issues/5), [#6](https://github.com/agorlov/lipid-example/issues/6), [#7](https://github.com/agorlov/lipid-example/issues/7), [#8](https://github.com/agorlov/lipid-example/issues/8).

**Comment by 0pdd** [comment]
@agorlov 4 puzzles [#36](https://github.com/agorlov/lipid-example/issues/36), [#39](https://github.com/agorlov/lipid-example/issues/39), [#40](https://github.com/agorlov/lipid-example/issues/40), [#42](https://github.com/agorlov/lipid-example/issues/42) are still not solved; solved: [#33](https://github.com/agorlov/lipid-example/issues/33), [#34](https://github.com/agorlov/lipid-example/issues/34), [#35](https://github.com/agorlov/lipid-example/issues/35), [#37](https://github.com/agorlov/lipid-example/issues/37), [#38](https://github.com/agorlov/lipid-example/issues/38), [#41](https://github.com/agorlov/lipid-example/issues/41), [#43](https://github.com/agorlov/lipid-example/issues/43), [#4](https://github.com/agorlov/lipid-example/issues/4), [#51](https://github.com/agorlov/lipid-example/issues/51), [#5](https://github.com/agorlov/lipid-example/issues/5), [#6](https://github.com/agorlov/lipid-example/issues/6), [#7](https://github.com/agorlov/lipid-example/issues/7), [#8](https://github.com/agorlov/lipid-example/issues/8).

**Comment by 0pdd** [comment]
@agorlov 3 puzzles [#36](https://github.com/agorlov/lipid-example/issues/36), [#39](https://github.com/agorlov/lipid-example/issues/39), [#42](https://github.com/agorlov/lipid-example/issues/42) are still not solved; solved: [#33](https://github.com/agorlov/lipid-example/issues/33), [#34](https://github.com/agorlov/lipid-example/issues/34), [#35](https://github.com/agorlov/lipid-example/issues/35), [#37](https://github.com/agorlov/lipid-example/issues/37), [#38](https://github.com/agorlov/lipid-example/issues/38), [#40](https://github.com/agorlov/lipid-example/issues/40), [#41](https://github.com/agorlov/lipid-example/issues/41), [#43](https://github.com/agorlov/lipid-example/issues/43), [#4](https://github.com/agorlov/lipid-example/issues/4), [#51](https://github.com/agorlov/lipid-example/issues/51), [#5](https://github.com/agorlov/lipid-example/issues/5), [#6](https://github.com/agorlov/lipid-example/issues/6), [#7](https://github.com/agorlov/lipid-example/issues/7), [#8](https://github.com/agorlov/lipid-example/issues/8).

**Comment by 0pdd** [comment]
@agorlov 2 puzzles [#39](https://github.com/agorlov/lipid-example/issues/39), [#42](https://github.com/agorlov/lipid-example/issues/42) are still not solved; solved: [#33](https://github.com/agorlov/lipid-example/issues/33), [#34](https://github.com/agorlov/lipid-example/issues/34), [#35](https://github.com/agorlov/lipid-example/issues/35), [#36](https://github.com/agorlov/lipid-example/issues/36), [#37](https://github.com/agorlov/lipid-example/issues/37), [#38](https://github.com/agorlov/lipid-example/issues/38), [#40](https://github.com/agorlov/lipid-example/issues/40), [#41](https://github.com/agorlov/lipid-example/issues/41), [#43](https://github.com/agorlov/lipid-example/issues/43), [#4](https://github.com/agorlov/lipid-example/issues/4), [#51](https://github.com/agorlov/lipid-example/issues/51), [#5](https://github.com/agorlov/lipid-example/issues/5), [#6](https://github.com/agorlov/lipid-example/issues/6), [#7](https://github.com/agorlov/lipid-example/issues/7), [#8](https://github.com/agorlov/lipid-example/issues/8).
