### ISSUE TITLE
Login and logout

### ISSUE THREAD

**Issue by agorlov** [agorlov/lipid-example#31]

**Comment by 0pdd** [comment]
@agorlov 3 puzzles [#46](https://github.com/agorlov/lipid-example/issues/46), [#47](https://github.com/agorlov/lipid-example/issues/47), [#48](https://github.com/agorlov/lipid-example/issues/48) are still not solved.

**Comment by 0pdd** [comment]
@agorlov 2 puzzles [#47](https://github.com/agorlov/lipid-example/issues/47), [#48](https://github.com/agorlov/lipid-example/issues/48) are still not solved; solved: [#46](https://github.com/agorlov/lipid-example/issues/46).

**Comment by 0pdd** [comment]
@agorlov the puzzle [#47](https://github.com/agorlov/lipid-example/issues/47) is still not solved; solved: [#46](https://github.com/agorlov/lipid-example/issues/46), [#48](https://github.com/agorlov/lipid-example/issues/48).
